### ISSUE TITLE
[Feature Request] Add option to change View Permission of YT Playlist

### ISSUE THREAD

**Issue by Rexadev** [yogeshwaran01/spotify-playlist-to-youtube-playlist#1]

**Comment by Rexadev** [comment]
@yogeshwaran01

**Comment by yogeshwaran01** [comment]
What do you mean default view?

**Comment by Rexadev** [comment]
Like --public not also flags like --private and --linkonly

maybe use syntax --permission public//private/linkonly

**Comment by yogeshwaran01** [comment]
Use `--public` flag to create public playlist. By default it create private playlist. I add `--only-link` later.

**Comment by yogeshwaran01** [comment]
I need 5 day of different outfit with use 3 shirt and 3 trousers. Recommend me shirt and trouser colour combination. One formal shoe to match all colour. Add any additional accessories

**Comment by Rexadev** [comment]
Would be simple to use syntax --permission public/private/linkonly and keep the private by default
@yogeshwaran01

**Comment by Rexadev** [comment]
@yogeshwaran01 what are your views ?

**Comment by yogeshwaran01** [comment]
> Would be simple to use syntax --permission public/private/linkonly and keep the private by default @yogeshwaran01

Ok I will add
