### ISSUE TITLE
After entering Spotify playlist ID it opens google error

### ISSUE THREAD

**Issue by Rexadev** [yogeshwaran01/spotify-playlist-to-youtube-playlist#2]
![image](https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist/assets/62152714/4a1fadb4-74ec-483e-b376-139cad44e07a)

**Comment by yogeshwaran01** [comment]
When creating client credentials use Desktop app as Application Type

![image](https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist/assets/66836092/ecc169d1-0e0a-4fb0-abb3-7efdd0b3f5bf)

**Comment by Rexadev** [comment]
Error 2 - Fixed error 1 now I get this

![image](https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist/assets/62152714/69f0a9e9-8115-476c-a2b0-e973d8e5505d)

@yogeshwaran01

**Comment by yogeshwaran01** [comment]
Verify your OAuth consent screen and add test user

**Comment by Rexadev** [comment]
> Verify your OAuth consent screen

How ?

> and add test user

Did it

**Comment by yogeshwaran01** [comment]
![image](https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist/assets/66836092/0f052887-4a1c-4f0c-898d-1514fb828fb0)

**Comment by Rexadev** [comment]
![image](https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist/assets/62152714/e69db037-c046-458c-a438-90339ca8f20a)

**Comment by Rexadev** [comment]
@yogeshwaran01

**Comment by yogeshwaran01** [comment]
Yes, Click continue to proceed.

**Comment by Rexadev** [comment]
> Yes, Click continue to proceed.

Thanks Working Now

**Comment by Rexadev** [comment]
@yogeshwaran01 You may use the screenshots and description in project wiki
