### ISSUE TITLE
[Feature Request] Add option to sync multiple playlists

### ISSUE THREAD

**Issue by Rexadev** [yogeshwaran01/spotify-playlist-to-youtube-playlist#3]
feature to add a --sync flag when first creating the playlist to automatedly add to a bat file lines `python main.py sync <spotify_playlist_id> <youtube_playlist_id>` that when run auto sync them

**Comment by yogeshwaran01** [comment]
It is unable to sync playlist just convert it. To convert it check [this](https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist#usage).

**Comment by Rexadev** [comment]
@yogeshwaran01 Will you add it in future ?

**Comment by yogeshwaran01** [comment]
> @yogeshwaran01 Will you add it in future ?
I already added it 
https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist#sync-your-youtube-playlist-with-your-spotify-playlist

**Comment by Rexadev** [comment]
Is there a feature to add a --sync flag when first creating the playlist to automatedly add to a bat file lines
 `python main.py sync <spotify_playlist_id> <youtube_playlist_id>`

**Comment by yogeshwaran01** [comment]
Ok I will implement it. Thank you for your suggestion

**Comment by Rexadev** [comment]
@yogeshwaran01 reopen this issue please
